### ISSUE TITLE
Metric name, spaces inside name should be removed ...

### ISSUE THREAD

**Issue by mohierf** [savoirfairelinux/mod-influxdb#23]
Metric name in the perfdata may include space character if you  have some metrics as of : 'Pages printed'=15c 

It should be interesting to remove all the space characters before storing the metric name in Influx ?

**Comment by ReAzem** [comment]
Hi,

Thank you for your feedback.

Indeed, it could be a good idea to remove the space characters, they would be replaced by spaces?

**Comment by mohierf** [comment]
Yes, underscore should be fine.

**Comment by ReAzem** [comment]
Fixed in bd83f52962835da23ace41a6b6873cc82c55d04e
