### ISSUE TITLE
How to check if it's work

### ISSUE THREAD

**Issue by lolostates** [savoirfairelinux/mod-influxdb#26]
Hello,

I'm testing your module with a fresh install of shinken. I have set only one host on my shinken for test purpose. After configuration of your plugins, how to check if it's works ?

I have set process_perfdata on shinken config, added the module on broker.conf, and then, no logging information on broker.log (execpt this : Correctly loaded mod-influxdb as a very-new-style shinken module :) )

Next, i can't see any data on influxdb (with a tcpdump or a query).
Do you have any method to check if all is fine ?

Thanks in advance, and thanks for your module !

Regards.

**Comment by aviau** [comment]
Hello,

Have you tried ``show series`` in InfluxDB?

Have you tried launching the broker manually (not in daemon) and see if there is an error?

**Comment by lolostates** [comment]
Hello,

Yes i have tried to "show series", but nothing return.
When i launch my broker with debug file option, no line speak about influxdb...

One more intresting thing: i have remove webui from broker.cfg and is loaded by my broker ... Very strange.

Do you want my broker config file ? My debug report ?

**Comment by lolostates** [comment]
Hello,

Ok i have changed mu broker config file and "influxdb_perfdata" must be set on brokers module list, not only influxdb.
Now it's ok, data has been sent to influxdb, but a 400 error has been returned: "error":"missing measurement"

**Comment by aviau** [comment]
What version of InfluxDB  are you using?

**Comment by lolostates** [comment]
I'm using influxdb 0.9.1 and name field has been renamed measurement.

**Comment by aviau** [comment]
Upstream mod-influxdb has renamed all fields to measurement.

Please use the latest version (from this repository - not shinken.io) and keep me updated :)

**Comment by lolostates** [comment]
Hello !

I have check with upstream version, and it work like a charm !
And other bug resolved, the module name on broker config file is : influxdb, not influxdb-perfdata.

No plan to update shinken.io ?

**Comment by aviau** [comment]
I have check with upstream version, and it work like a charm !

Nice!

> No plan to update shinken.io ?

I just updated it, for you! <3 It should be online in a few minutes.
