### ISSUE TITLE
Field type conflict

### ISSUE THREAD

**Issue by YBinnenweg** [savoirfairelinux/mod-influxdb#28]
Hi,

While playing around with InfluxDB and mod-influxdb to fill it with data from Shinken I've encountered a problem when filling it with ping data.
As you may or may not know, the type of a field in InfluxDB is defined by the first value written to it. ([source](https://influxdb.com/docs/v0.9/write_protocols/line.html])) And this is where the problems start, because there is no standardized way that mod-influxdb writes data to the database, it's possible to get conflicts. In my case there are a bunch of hosts that are unreachable and thus the ping plugin (check_ping from nagios-plugins) returns a big number, which sets the field type to int64. Now my next host is actually online and returns a float. (24.78ms for example) When it tries to write this data, it gives a field type conflict.
I've come up with an ugly hack to work around this, but because testing of this hack is very limited, I have no idea if it will conflict with other nagios plugins.
In [module.py at line 105](https://github.com/savoirfairelinux/mod-influxdb/blob/master/module/module.py#L105) replace the for in statement with this one:
```python
for mapping in fields_mappings:
    if 'value' in mapping:
        value = float(getattr(e, mapping[0], None))
    else:
        value = getattr(e, mapping[0], None)
    if value is not None:
        if 'value' in mapping:
            fields[mapping[1]] = float(value)
        else:
            fields[mapping[1]] = value
```
What this does is check if the data that's about to be written is going to be written to the field "value". If it is, it makes the value a float.

I don't think this is a permanent fix for this problem, feel free to suggest something that would work better! (hopefully more compatible too)

**Comment by aviau** [comment]
Hello,

Thank you for the detailed bug report. You analysis of the issue is is exact.

I think that the solution is to never create points with integers.

```python
for mapping in fields_mappings:
    value = getattr(e, mapping[0], None)
    if value is not None:
        if isinstance(value, int):
            value = float(value)
        fields[mapping[1]] = value
```

**Comment by YBinnenweg** [comment]
Hello @aviau,

Thank you for looking into it so quickly! I've just tried your branch and I can confirm that it gives me exactly the same results, it works perfectly!

A quick note for other people:
You have to delete your series and measurements from your InfluxDB, otherwise it'll still be stuck on the old types.

**Comment by aviau** [comment]
Great!

Thank you for reporting back :)
